title = "removeImage"
category = "images"
isScreen = false
summary = "Removes an image from memory."
description = ""
example = """
$.screen( "300x200" );
var monkey = $.loadImage( "/images/monkey.png" );
$.ready( function () {
\t$.drawImage( monkey, 150, 100, 0, 0.5, 0.5 );
\t$.removeImage( monkey );
\t$.drawImage( monkey, 200, 150 );
} );
"""

[[parameters]]
name = "name"
type = "any"
description = "The name or id of the image to remove."

[[returns]]
type = "void"
description = "This function does not return a value."
