title = "setPixelMode"
category = "graphics"
isScreen = true
summary = "Toggles between pixel mode and anti-aliased drawing modes."
description = ""
example = """
$.screen( "300x200" );
$.setColor( 4 );
$.line( 30, 80, 270, 50 );
$.setPixelMode( false );
$.line( 30, 120, 270, 90 );
"""

[[parameters]]
name = "isEnabled"
type = "any"
description = "If set to true use the pixel mode otherwise use anit-aliased mode."

[[returns]]
type = "void"
description = "This function does not return a value."
