title = "startKeyboard"
category = "keyboard"
isScreen = false
summary = "Starts keyboard input monitoring."
description = """
Starts the keyboard input monitoring system. This initializes event listeners for keydown and
keyup events.

Note: the keyboard automatically starts when key commands are called, but this command can be
used to restart it after calling stopKeyboard.
"""
example = """
$.screen( "300x200" );

var hitboxColor = 2;
var hitbox = {
\t"x": 175,
\t"y": 75,
\t"width": 100,
\t"height": 100
};
var msg = "";
var isGreen = true;

$.onclick( clickBox, false, hitbox );
$.onkey( "any", "down", function ( key ) {
\tmsg = "You pressed " + key.key + ".";
\tdrawScreen();
} );
$.onkey( "any", "up", function ( key ) {
\tmsg = "";
\tdrawScreen();
} );

drawScreen();

function drawScreen() {
\t$.cls();
\t$.setColor( 7 );
\t$.print( "Press any key" );
\t$.print( "Click the box to toggle keyboard." );
\t$.print( msg );
\t$.setColor( hitboxColor );
\t$.rect( hitbox );
}

function clickBox() {
\tisGreen = !isGreen;
\tif( isGreen ) {
\t\thitboxColor = 2;
\t\t$.startKeyboard();
\t} else {
\t\t$.stopKeyboard();
\t\thitboxColor = 4;
\t}
\tdrawScreen();
}
"""

parameters = [ ]
[[returns]]
type = "void"
description = "This function does not return a value."
