title = "stopTouch"
category = "touch"
isScreen = true
summary = "Stops the touch event listeners for the screen."
description = ""
example = """
$.screen( "100x100" );
$.startTouch();
$.setPinchZoom( false );
var count = 5;
$.print( count + " touches left" );
$.ontouch( "start", function ( touches ) {
\t$.setColor( Math.floor( Math.random() * 9 ) + 1 );
\t$.print( --count + " touches left" );
\tvar touch = touches[ 0 ];
\t$.pset( touch.x, touch.y );
\tif( count === 0 ) {
\t\t$.stopTouch();
\t}
} );
"""

parameters = [ ]
[[returns]]
type = "void"
description = "This function does not return a value."
