title = "height"
category = "view"
isScreen = true
summary = "Returns the screen or active view height in pixels."
description = """
Gets the internal height of the active screen's canvas. This is the logical height used for drawing
operations, which may differ from the CSS display size.

If there is an active view using pushView then it will return the height of the local viewport area and not the screen height.
"""
example = """
$.screen( "320x200" );
const h = $.height();
$.print( `Screen Height: ${h}` );
$.print( `Canvas CSS height: ${$.canvas().offsetHeight}` );
$.pushView( 30, 20, 50, 50 );
$.print( `Viewport Height: ${$.height()} ` );
$.popView();
"""

[[returns]]
type = "number"
description = "Screen or local view height in pixels."
