title = "width"
category = "view"
isScreen = true
summary = "Returns the screen or active view width in pixels."
description = """
Gets the internal width of the active screen's canvas. This is the logical width used for drawing
operations, which may differ from the CSS display size.

If there is an active view using pushView then it will return the width of the local viewport area and not the screen width.
"""
example = """
$.screen( "320x200" );
const w = $.width();
$.print( `Screen Width: ${w} ` );
$.print( `Canvas CSS width: ${$.canvas().offsetWidth}` );
$.pushView( 30, 20, 50, 50 );
$.print( `Viewport Width: ${$.width()} ` );
$.popView();
"""

[[returns]]
type = "number"
description = "Screen or local view width in pixels."
