# Commands and objects removed in Pi.js 2.3.
methods = [
	"ingamepad",
	"inkey",
	"inmouse",
	"inpress",
	"intouch",
	"offclick",
	"offkey",
	"offmouse",
	"offpress",
	"offtouch",
	"onGamepadConnected",
	"onGamepadDisconnected",
	"onclick",
	"onkey",
	"onmouse",
	"onpress",
	"ontouch",
	"setEnableContextMenu",
	"setGamepadSensitivity"
]
objects = []
