// Help text: the pages of the HELP screen and the pop-up tips shown while TIPS is on.

// One line per row of the help screen, at most 69 characters. A line starting with "#" is a
// section heading and a line starting with "-" is a dimmed note.
const HELP_TEXT = `# WELCOME
PI.JS TRACKS IS A MUSIC MAKER. A SONG IS A SET OF TRACKS, AND EACH
TRACK IS ONE INSTRUMENT PLAYING NOTES ON A GRID. TIME RUNS LEFT TO
RIGHT, AND HIGHER NOTES SIT HIGHER UP.
- NOT SURE WHAT A BUTTON DOES? CLOSE THIS, TURN ON TIPS (BOTTOM RIGHT)
- AND POINT AT IT.

# QUICK START
1. PRESS PLAY (OR SPACE) TO HEAR THE SONG. PRESS IT AGAIN TO STOP.
2. PICK A TRACK ON THE LEFT: LEAD, BASS, DRUMS...
3. CLICK THE GRID TO ADD A NOTE. CLICK A NOTE TO REMOVE IT.
4. STUCK? MAGIC WRITES A MELODY, CHORDS, A BASSLINE OR A BEAT.
5. LOAD HAS DEMO SONGS TO TAKE APART. SAVE KEEPS YOUR OWN SONG.

# THE TOP BAR
PLAY       STARTS THE SONG FROM THE BEGINNING, OR STOPS IT.
LOOP       ON: THE SONG REPEATS. OFF: IT PLAYS ONCE AND STOPS.
BPM        THE SPEED, IN BEATS PER MINUTE (32 TO 255). USE - AND +,
           OR ROLL THE MOUSE WHEEL OVER THE NUMBER.
KEY        THE NOTE THE SONG IS BUILT AROUND. THE ARROWS MOVE EVERY
           NOTE UP OR DOWN WITH IT.
SCALE      THE SET OF NOTES THAT SOUND RIGHT TOGETHER. MAJOR IS
           BRIGHT, MINOR IS SAD OR MOODY. CHANGING IT MOVES YOUR
           NOTES TO FIT, SO A HAPPY TUNE CAN TURN SAD.
BARS       THE LENGTH OF THE SONG, 1 TO 32 BARS. A BAR IS 16 STEPS.
           REMOVING A BAR REMOVES ITS NOTES (UNDO BRINGS THEM BACK).

# TRACKS
THE LIST ON THE LEFT HOLDS UP TO 8 TRACKS. CLICK ONE TO EDIT IT.
M          MUTE: SILENCES THE TRACK.
S          SOLO: PLAYS ONLY THE SOLOED TRACKS.
+ MELODY   ADDS A TRACK THAT PLAYS NOTES.
+ DRUMS    ADDS A DRUM TRACK WITH 8 DRUM SOUNDS.
THE STRIP BESIDE M AND S FLASHES WHEN THE TRACK PLAYS A NOTE. THE
BARS BELOW THE LIST SHOW THE SOUND THAT IS PLAYING.

# THE SELECTED TRACK
THE TWO ROWS ABOVE THE GRID BELONG TO THE SELECTED TRACK.
NAME       CLICK IT, TYPE A NEW NAME, AND PRESS ENTER.
SOUND      THE ARROWS STEP THROUGH THE SOUNDS. CLICK THE SOUND'S NAME
           TO PICK ONE FROM THE FULL LIST.
EDIT       OPENS THE SOUND EDITOR TO SHAPE THE SOUND YOURSELF.
VOL        HOW LOUD THE TRACK IS.
PAN        LEFT OR RIGHT SPEAKER. THE MIDDLE IS BOTH.
DEL        DELETES THE TRACK (UNDO BRINGS IT BACK).

# WRITING NOTES
1/16 TO 1  THE LENGTH OF NEW NOTES. 1 IS A WHOLE BAR, 1/16 ONE STEP.
CLICK AN EMPTY CELL TO ADD A NOTE. KEEP HOLDING AND DRAG RIGHT TO
MAKE IT LONGER.
CLICK A NOTE TO REMOVE IT.
DRAG A NOTE TO MOVE IT. DRAG THE END OF A LONG NOTE TO RESIZE IT.
RIGHT-CLICK A NOTE TO MAKE IT SOFTER: 100%, 60%, 30%, THEN LOUD.
CLICK A NOTE NAME ON THE LEFT OF THE GRID TO HEAR THAT NOTE.
FAINT OUTLINES ARE THE NOTES OF YOUR OTHER MELODY TRACKS, SO YOU CAN
SEE HOW THE PARTS FIT TOGETHER.

# STAYING IN KEY
LOCK       ON: THE GRID SHOWS ONLY THE NOTES OF THE SCALE, SO NOTHING
           SOUNDS WRONG. OFF: ALL 12 NOTES ARE SHOWN.
THE YELLOW NOTE NAMES ARE THE KEY NOTE, WHICH FEELS LIKE HOME.
THE BRIGHTER ROWS ARE THE NOTES OF EACH BAR'S CHORD. THEY ARE THE
SAFEST NOTES TO USE IN THAT BAR.

# DRUM TRACKS
A DRUM TRACK HAS ONE ROW FOR EACH DRUM: KICK, SNARE, CLAP, HAT, OPEN
HAT, LOW TOM, HIGH TOM AND PERCUSSION.
CLICK A CELL TO ADD OR REMOVE A HIT. DRAG TO PAINT SEVERAL.
RIGHT-CLICK A HIT TO MAKE IT SOFTER.

# CHORDS
A CHORD IS A GROUP OF NOTES THAT SOUND GOOD TOGETHER. EVERY BAR OF
THE SONG HAS ONE.
CHD ROW    ABOVE THE GRID. CLICK A BAR'S CHORD TO CHANGE IT.
           RIGHT-CLICK GOES BACK.
CHORDS     BOTTOM LEFT. PICKS A READY-MADE CHORD PATTERN FOR THE
           WHOLE SONG. IT SAYS CUSTOM ONCE YOU CHANGE A BAR YOURSELF.
MAGIC FOLLOWS THE CHORDS, SO CHANGE THE CHORDS FIRST, THEN USE MAGIC.

# MAGIC, CLEAR, DOUBLE AND REC
MAGIC      WRITES A PART FOR THE SELECTED TRACK: A MELODY, CHORDS,
           AN ARPEGGIO OR A BASSLINE, OR A BEAT FOR A DRUM TRACK.
           IT REPLACES THE TRACK'S NOTES. NEW MELODY IS DIFFERENT
           EVERY TIME.
CLEAR      REMOVES EVERY NOTE FROM THE SELECTED TRACK.
DOUBLE     MAKES THE SONG TWICE AS LONG BY COPYING IT. THEN CHANGE
           THE SECOND HALF.
REC        RECORDS WHAT YOU TYPE. TURN IT ON, PRESS PLAY, AND PLAY
           THE PIANO KEYS. NOTES LAND WHERE THE SONG IS PLAYING.

# MOVING AROUND
THE GRID SHOWS 2 BARS AT A TIME.
THE ARROW BUTTONS ABOVE THE GRID, OR THE LEFT AND RIGHT KEYS, CHANGE
THE PAGE. WHILE THE SONG PLAYS, THE GRID FOLLOWS IT.
MAP        THE STRIP BELOW THE GRID SHOWS THE WHOLE TRACK. CLICK OR
           DRAG IN IT TO JUMP.
THE MOUSE WHEEL, THE UP AND DOWN KEYS, OR THE SCROLL BAR ON THE RIGHT
MOVE TO HIGHER AND LOWER NOTES.

# PLAYING LIVE
YOUR KEYBOARD PLAYS THE SELECTED TRACK LIKE A PIANO.
LOWER ROW  Z X C V B N M ARE THE WHITE KEYS, AND S D G H J THE BLACK
           KEYS BETWEEN THEM.
UPPER ROW  Q W E R T Y U, ONE OCTAVE HIGHER, WITH 2 3 5 6 7 AS THE
           BLACK KEYS.
ON A DRUM TRACK, Z X C V B N M AND THE COMMA KEY PLAY THE 8 DRUMS.

# EFFECTS
THE SLIDERS ALONG THE BOTTOM CHANGE THE WHOLE SONG.
REV        REVERB: THE SOUND OF A BIG ROOM.
ECHO       REPEATS THE SOUND IN TIME WITH THE SONG.
CHOR       CHORUS: A WIDER, SHIMMERING SOUND.
CRSH       CRUSH: A ROUGH, CRUNCHY OLD-COMPUTER SOUND.
VOL        HOW LOUD EVERYTHING IS.

# CHOOSING A SOUND
CLICK THE SOUND'S NAME ABOVE THE GRID. MELODY TRACKS HAVE 20 SOUNDS
IN FIVE GROUPS: LEAD, KEYS, PAD, PLUCK AND BASS. DRUM TRACKS HAVE 3
KITS. CLICK ONE TO HEAR IT. YOUR NOTES STAY THE SAME.

# THE SOUND EDITOR
EDIT OPENS IT. EVERY CHANGE PLAYS THE SOUND SO YOU CAN HEAR IT.
WAVE       THE RAW TONE. SINE IS SOFT, TRI IS MELLOW, SQR AND THE TWO
           PULSES (P-25, P-12) ARE CLASSIC GAME SOUNDS, SAW IS
           BRIGHT, AND NOISE AND PINK ARE HISS FOR DRUMS.
VOLUME     HOW LOUD THE SOUND IS.
ATTACK     HOW LONG THE SOUND TAKES TO FADE IN.
DECAY      HOW LONG IT TAKES TO DROP TO THE SUSTAIN LEVEL.
SUSTAIN    HOW LOUD IT STAYS WHILE THE NOTE IS HELD.
RELEASE    HOW LONG IT RINGS AFTER THE NOTE ENDS.
STYLE      SHORT CUTS EACH NOTE OFF EARLY, SMOOTH JOINS THE NOTES.
FILTER     LOW KEEPS THE DEEP PART OF THE SOUND, HIGH KEEPS THE
           BRIGHT PART, BAND KEEPS THE MIDDLE.
CUTOFF     WHERE THE FILTER CUTS.
RESO       ADDS A WHISTLING EDGE AT THE CUTOFF.
SWEEP      MOVES THE CUTOFF AT THE START OF EACH NOTE.
SWP TIME   HOW LONG THE SWEEP TAKES.
VIBRATO    WOBBLES THE PITCH.
TREMOLO    WOBBLES THE VOLUME.
ARPEGGIO   TURNS ONE NOTE INTO A FAST RUN OF NOTES.
ARP RATE   HOW FAST THE ARPEGGIO RUNS.
DRUMS HAVE THEIR OWN SOUND EACH. PICK THE DRUM AT THE TOP. THEY ADD:
PITCH      THE DRUM'S STARTING PITCH.
DROP TO    THE PITCH IT FALLS TO, FOR KICKS AND TOMS.
RING       HOW MANY STEPS THE DRUM RINGS.
RESET      PUTS THE SOUND BACK TO HOW IT CAME.
THE KEYBOARD AT THE BOTTOM PLAYS THE SOUND. CLICK IT OR TYPE.

# SAVING AND LOADING
THE SONG NAME IS AT THE BOTTOM LEFT. CLICK IT TO RENAME THE SONG.
NEW        STARTS A BLANK SONG.
SAVE       KEEPS THE SONG IN THIS BROWSER UNDER ITS NAME. SAVING
           AGAIN WITH THE SAME NAME REPLACES IT.
LOAD       MY SONGS LISTS THE SONGS YOU SAVED. DEMOS HAS SONGS TO
           LEARN FROM. IMPORT FILE READS A SONG FILE.
EXPORT     DOWNLOADS THE SONG AS A .JS FILE TO KEEP OR SHARE.
WAV        RECORDS THE SONG AS AN AUDIO FILE. IT RECORDS WHILE THE
           SONG PLAYS, 1, 2 OR 4 TIMES. MUTED TRACKS ARE LEFT OUT.
UNDO       TAKES BACK THE LAST CHANGE, UP TO 100 CHANGES.
REDO       PUTS BACK WHAT UNDO TOOK AWAY.
- SAVED SONGS LIVE IN THIS BROWSER ON THIS COMPUTER. EXPORT A SONG TO
- KEEP A COPY ANYWHERE ELSE. THE SONG YOU ARE WORKING ON IS ALSO KEPT
- AUTOMATICALLY, SO IT IS STILL HERE WHEN YOU COME BACK.

# YOUR SONG IS CODE
CODE SHOWS THE SONG AS PI.JS COMMANDS THAT PLAY IN ANY PI.JS PROGRAM.
COPY CODE  COPIES THE CODE SO YOU CAN PASTE IT INTO YOUR PROGRAM.
EXPORT .JS DOWNLOADS THE CODE AS A FILE.
PASTE CODE LOADS CODE YOU COPIED. CTRL+V DOES THE SAME ANYWHERE.
YOU CAN ALSO DROP A SONG FILE ONTO THE PAGE.
IF YOU CHANGE THE PLAY() TEXT BY HAND, THE CHANGES LOAD TOO. PLAIN
PI.JS PLAY() CODE FROM OTHER PROGRAMS LOADS AS NEW TRACKS.

# KEYS
SPACE      PLAY OR STOP
CTRL+Z     UNDO
CTRL+Y     REDO
ESC        CLOSE A WINDOW
LEFT RIGHT CHANGE THE PAGE
UP DOWN    SCROLL THE NOTES
Z TO M     PLAY NOTES, OR THE 8 DRUMS
Q TO U     PLAY NOTES ONE OCTAVE HIGHER
CTRL+V     LOAD CODE YOU COPIED`;

export const HELP_LINES = HELP_TEXT.split( "\n" ).map( line => {
	if( line.startsWith( "# " ) ) {
		return { "kind": "head", "text": line.slice( 2 ) };
	}
	if( line.startsWith( "- " ) ) {
		return { "kind": "note", "text": line.slice( 2 ) };
	}
	return { "kind": "text", "text": line };
} );

// Tips by widget id. An id that ends in a number (a track's mute button, a demo song) uses
// the entry without the number.
const TIPS = {
	// Top bar
	"play": "PLAYS THE SONG FROM THE START, OR STOPS IT. SPACE DOES THE SAME.",
	"loop": "ON: THE SONG REPEATS UNTIL YOU STOP IT. OFF: IT PLAYS ONCE.",
	"tempo-": "SLOWER. HOLD TO KEEP GOING.",
	"tempo+": "FASTER. HOLD TO KEEP GOING.",
	"tempo": "THE SPEED IN BEATS PER MINUTE. ROLL THE MOUSE WHEEL HERE TO CHANGE IT.",
	"key-": "MOVES THE WHOLE SONG DOWN ONE NOTE.",
	"key+": "MOVES THE WHOLE SONG UP ONE NOTE.",
	"scale-": "PREVIOUS SCALE. A SCALE IS THE SET OF NOTES THE SONG USES. YOUR NOTES MOVE TO FIT.",
	"scale+": "NEXT SCALE. A SCALE IS THE SET OF NOTES THE SONG USES. YOUR NOTES MOVE TO FIT.",
	"bars-": "MAKES THE SONG ONE BAR SHORTER. NOTES IN THE LAST BAR ARE REMOVED.",
	"bars+": "MAKES THE SONG ONE BAR LONGER, UP TO 32 BARS.",

	// Track list
	"track": "A TRACK: ONE INSTRUMENT AND ITS NOTES. CLICK TO EDIT IT.",
	"mute": "MUTE: SILENCES THIS TRACK.",
	"solo": "SOLO: PLAYS ONLY THE SOLOED TRACKS.",
	"addm": "ADDS A TRACK THAT PLAYS NOTES. A SONG CAN HAVE 8 TRACKS.",
	"addd": "ADDS A DRUM TRACK. A SONG CAN HAVE 8 TRACKS.",
	"vis": "SHOWS THE SOUND THAT IS PLAYING: LOW NOTES ON THE LEFT, HIGH ON THE RIGHT.",

	// Selected track
	"tname": "THE TRACK'S NAME. CLICK, TYPE A NEW ONE, AND PRESS ENTER.",
	"inst-": "PREVIOUS SOUND.",
	"inst": "THE TRACK'S SOUND. CLICK TO PICK ONE FROM THE FULL LIST.",
	"inst+": "NEXT SOUND.",
	"sound": "OPENS THE SOUND EDITOR, WHERE YOU SHAPE THIS TRACK'S SOUND.",
	"tvol": "HOW LOUD THIS TRACK IS.",
	"tpan": "LEFT OR RIGHT SPEAKER. THE MIDDLE IS BOTH.",
	"tdel": "DELETES THIS TRACK. UNDO BRINGS IT BACK.",
	"len": "THE LENGTH OF THE NOTES YOU ADD. 1 IS A WHOLE BAR.",
	"lock": "ON: THE GRID SHOWS ONLY NOTES IN THE SONG'S SCALE, SO NOTHING SOUNDS WRONG.",
	"magic": "WRITES A MELODY, CHORDS, BASS OR BEAT FOR THIS TRACK. IT REPLACES THE TRACK'S NOTES.",
	"mg": "WRITES THIS KIND OF PART FOR THE TRACK, FOLLOWING THE SONG'S CHORDS.",
	"clear": "REMOVES EVERY NOTE FROM THIS TRACK. UNDO BRINGS THEM BACK.",
	"double": "MAKES THE SONG TWICE AS LONG BY COPYING IT.",
	"rec": "RECORDS THE NOTES YOU TYPE WHILE THE SONG PLAYS.",
	"page-": "SHOWS THE EARLIER PART OF THE SONG. THE LEFT KEY DOES THE SAME.",
	"page+": "SHOWS THE LATER PART OF THE SONG. THE RIGHT KEY DOES THE SAME.",

	// Grid
	"chord": "THIS BAR'S CHORD. CLICK TO CHANGE IT, RIGHT-CLICK TO GO BACK.",
	"label": "NOTE NAMES. CLICK ONE TO HEAR IT. YELLOW IS THE KEY NOTE.",
	"label-drums": "THE DRUMS. CLICK ONE TO HEAR IT.",
	"grid": "CLICK TO ADD A NOTE AND DRAG RIGHT TO MAKE IT LONGER. CLICK A NOTE TO REMOVE IT, " +
		"DRAG IT TO MOVE IT, RIGHT-CLICK IT TO MAKE IT SOFTER.",
	"grid-drums": "CLICK TO ADD OR REMOVE A HIT. DRAG TO PAINT SEVERAL. RIGHT-CLICK A HIT TO MAKE IT SOFTER.",
	"up": "SHOWS HIGHER NOTES.",
	"down": "SHOWS LOWER NOTES.",
	"vscroll": "DRAG TO MOVE TO HIGHER OR LOWER NOTES.",
	"map": "THE WHOLE TRACK. THE WHITE BOX IS THE PART THE GRID SHOWS. CLICK TO JUMP.",

	// Bottom bar
	"prog-": "PREVIOUS CHORD PATTERN.",
	"prog": "THE SONG'S CHORD PATTERN. CLICK FOR THE NEXT ONE. CUSTOM MEANS YOU CHANGED A BAR YOURSELF.",
	"prog+": "NEXT CHORD PATTERN.",
	"fx-reverb": "REVERB: THE SOUND OF A BIG ROOM.",
	"fx-echo": "ECHO: REPEATS THE SOUND IN TIME WITH THE SONG.",
	"fx-chorus": "CHORUS: A WIDER, SHIMMERING SOUND.",
	"fx-crush": "CRUSH: A ROUGH, CRUNCHY OLD-COMPUTER SOUND.",
	"master": "HOW LOUD EVERYTHING IS.",
	"title": "THE SONG'S NAME. CLICK, TYPE A NEW ONE, AND PRESS ENTER.",
	"b-NEW": "STARTS A BLANK SONG. UNDO BRINGS THE OLD ONE BACK.",
	"b-SAVE": "KEEPS THE SONG IN THIS BROWSER UNDER ITS NAME.",
	"b-LOAD": "OPENS YOUR SAVED SONGS, THE DEMO SONGS, OR A SONG FILE.",
	"b-CODE": "SHOWS THE SONG AS PI.JS CODE YOU CAN USE IN YOUR OWN PROGRAMS.",
	"b-EXPORT": "DOWNLOADS THE SONG AS A .JS FILE TO KEEP OR SHARE.",
	"b-WAV": "RECORDS THE SONG AS A .WAV AUDIO FILE.",
	"b-UNDO": "TAKES BACK THE LAST CHANGE. CTRL+Z DOES THE SAME.",
	"b-REDO": "PUTS BACK WHAT UNDO TOOK AWAY. CTRL+Y DOES THE SAME.",
	"b-HELP": "OPENS THE GUIDE TO EVERYTHING IN PI.JS TRACKS.",
	"b-TIPS": "TURNS THESE TIPS ON AND OFF.",

	// Windows
	"ov-x": "CLOSES THIS WINDOW. ESC DOES THE SAME.",
	"kit": "USES THIS DRUM KIT. YOUR HITS STAY THE SAME.",
	"pre-": "USES THIS SOUND AND PLAYS IT. YOUR NOTES STAY THE SAME.",
	"ins-edit": "OPENS THE SOUND EDITOR FOR THIS TRACK.",
	"ins-done": "CLOSES THIS WINDOW.",
	"drum": "PICKS THE DRUM TO EDIT, AND PLAYS IT.",
	"c-wave": "THE RAW TONE OF THE SOUND. NOISE AND PINK ARE HISS, FOR DRUMS.",
	"c-style": "SHORT CUTS EACH NOTE OFF EARLY. SMOOTH JOINS THE NOTES TOGETHER.",
	"c-filter": "LOW KEEPS THE DEEP PART OF THE SOUND, HIGH THE BRIGHT PART, BAND THE MIDDLE.",
	"c-arp": "TURNS EACH NOTE INTO A FAST RUN OF NOTES.",
	"p-volume": "HOW LOUD THE SOUND IS.",
	"p-attack": "HOW LONG THE SOUND TAKES TO FADE IN.",
	"p-decay": "HOW LONG THE SOUND TAKES TO DROP TO THE SUSTAIN LEVEL.",
	"p-sustain": "HOW LOUD THE SOUND STAYS WHILE THE NOTE IS HELD.",
	"p-release": "HOW LONG THE SOUND RINGS AFTER THE NOTE ENDS.",
	"p-pitch": "THE DRUM'S STARTING PITCH. NOTE USES THE PITCH OF THE NOTE INSTEAD.",
	"p-pitchEnd": "THE PITCH THE DRUM FALLS TO. GOOD FOR KICKS AND TOMS.",
	"p-ring": "HOW MANY STEPS THE DRUM RINGS.",
	"p-cutoff": "WHERE THE FILTER CUTS THE SOUND.",
	"p-resonance": "ADDS A WHISTLING EDGE AT THE CUTOFF.",
	"p-envAmount": "MOVES THE CUTOFF AT THE START OF EACH NOTE, FOR A WOW OR A PLUCK.",
	"p-envDecay": "HOW LONG THE SWEEP TAKES.",
	"p-vibrato": "WOBBLES THE PITCH.",
	"p-tremolo": "WOBBLES THE VOLUME.",
	"p-arpRate": "HOW FAST THE ARPEGGIO RUNS.",
	"test": "PLAYS THIS DRUM.",
	"keys": "PLAYS THE SOUND. CLICK A KEY, OR TYPE Z-M AND Q-U.",
	"snd-reset": "PUTS THE SOUND BACK TO HOW IT CAME.",
	"snd-done": "CLOSES THE SOUND EDITOR. YOUR CHANGES ARE KEPT.",
	"code-up": "SCROLLS UP.",
	"code-dn": "SCROLLS DOWN.",
	"code-scroll": "DRAG TO SCROLL.",
	"code-copy": "COPIES THE CODE SO YOU CAN PASTE IT INTO A PI.JS PROGRAM.",
	"code-save": "DOWNLOADS THE CODE AS A .JS FILE.",
	"code-paste": "LOADS SONG CODE YOU COPIED. CTRL+V DOES THE SAME.",
	"code-load": "LOADS A SONG FROM A FILE.",
	"load-tab-saved": "SHOWS THE SONGS YOU SAVED IN THIS BROWSER.",
	"load-tab-demos": "SHOWS THE DEMO SONGS.",
	"load-import": "LOADS A SONG FROM A FILE YOU EXPORTED.",
	"demo": "LOADS THIS DEMO SONG. UNDO GOES BACK TO YOUR SONG.",
	"saved": "LOADS THIS SONG. UNDO GOES BACK TO THE SONG YOU HAVE NOW.",
	"saved-del": "REMOVES THIS SONG FROM THE BROWSER FOR GOOD. CLICK TWICE TO CONFIRM.",
	"load-up": "SHOWS EARLIER SONGS.",
	"load-dn": "SHOWS MORE SONGS.",
	"loops": "HOW MANY TIMES THE SONG PLAYS IN THE RECORDING.",
	"rec-go": "STARTS RECORDING. IT TAKES AS LONG AS THE SONG.",
	"rec-stop": "STOPS THE RECORDING WITHOUT SAVING.",
	"wav-save": "DOWNLOADS THE RECORDING AS A .WAV FILE.",
	"wav-again": "THROWS THIS RECORDING AWAY AND STARTS OVER.",
	"wav-close": "CLOSES THIS WINDOW.",
	"wav-back": "GOES BACK TO TRY AGAIN.",
	"help-up": "SCROLLS UP.",
	"help-dn": "SCROLLS DOWN.",
	"help-scroll": "DRAG TO SCROLL.",
	"help-ok": "CLOSES THE GUIDE."
};

const TIP_PREFIXES = [ "pre-", "c-wave", "c-style", "c-filter", "c-arp" ];

// The tip for a widget id, or null when it has none.
export function tipFor( id ) {
	if( TIPS[ id ] ) {
		return TIPS[ id ];
	}
	const base = id.replace( /\d+$/, "" );
	if( TIPS[ base ] ) {
		return TIPS[ base ];
	}
	const prefix = TIP_PREFIXES.find( p => id.startsWith( p ) );
	return prefix ? TIPS[ prefix ] : null;
}

// Breaks text into lines of at most `chars` characters, at spaces.
export function wrapText( str, chars ) {
	const lines = [];
	let line = "";
	for( const word of str.split( " " ) ) {
		if( line && line.length + 1 + word.length > chars ) {
			lines.push( line );
			line = word;
		} else {
			line = line ? line + " " + word : word;
		}
	}
	if( line ) {
		lines.push( line );
	}
	return lines;
}
